### ISSUE TITLE
Add logo & favicon

### ISSUE THREAD

**Issue by aq1018** [BulletForge/danmaku_site#31]

**Comment by Blargel** [comment]
Logo with text beneath icon: https://cdn.discordapp.com/attachments/912517156724441109/912811239107870780/Logos_Logo-Column.svg

Logo with text to the right of icon: https://cdn.discordapp.com/attachments/912517156724441109/912811239284039680/Logos_Logo-Row.svg

Logo only: https://cdn.discordapp.com/attachments/912517156724441109/912811239435010068/Logos_Emblem.svg
