### ISSUE TITLE
Redirect people going to bulletforge.herokuapp.com to bulletforge.org

### ISSUE THREAD

**Issue by Blargel** [BulletForge/danmaku_site#41]
Uploads to S3 do not work from bulletforge.herokuapp.com due to CORS policy. We need to redirect people who are still using the herokuapp domain to the new domain.

Alternatively, we can loosen up the CORS policy to include the herokuapp domain.

**Comment by aq1018** [comment]
This can be done with a custom rack middleware that detects 'HOST', if it is heroku, send redirect.

**Comment by Blargel** [comment]
Looks good.
