### ISSUE TITLE
Better meta tags in head

### ISSUE THREAD

**Issue by Blargel** [BulletForge/danmaku_site#42]
Currently, every page has the same meta tags. The title is always "BulletForge", and the description is always "Dedicated Danmakufu Project Hosting". This should be improved so that, for example, in a project page, the title becomes "BulletForge - {project.title}" or something like that.

**Comment by Blargel** [comment]
@aq1018 It looks like you're passing the description in raw when applicable, which means it will give the raw markdown syntax. We should try to strip the extra markdown syntax out in this case.

**Comment by Blargel** [comment]
While we're at it, let's also add the project's cover image if applicable.

**Comment by aq1018** [comment]
Added social meta tags for facebook open graph and twitter card. I think Discord uses those meta tags as well.
